.TH "args" 3 "Fri Dec 4 2020" "Version 1.00" "Download" \" -*- nroff -*-
.ad l
.nh
.SH NAME
args \- Struct that keeps the data from the URL argument\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <args\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBuser\fP"
.br
.RI "User used for Login\&. "
.ti -1c
.RI "char * \fBpassword\fP"
.br
.RI "Password used for Login\&. "
.ti -1c
.RI "char * \fBhost\fP"
.br
.RI "Host name in URL\&. "
.ti -1c
.RI "char * \fBpath\fP"
.br
.RI "Path to the file\&. "
.ti -1c
.RI "char * \fBfile_name\fP"
.br
.RI "Name of the File\&. "
.ti -1c
.RI "char * \fBhost_name\fP"
.br
.RI "Host Name from gethostbyname() "
.ti -1c
.RI "char * \fBip\fP"
.br
.RI "IP Adress from gethostbyname() "
.in -1c
.SH "Detailed Description"
.PP 
Struct that keeps the data from the URL argument\&. 
.SH "Field Documentation"
.PP 
.SS "char* file_name"

.PP
Name of the File\&. 
.SS "char* host"

.PP
Host name in URL\&. 
.SS "char* host_name"

.PP
Host Name from gethostbyname() 
.SS "char* ip"

.PP
IP Adress from gethostbyname() 
.SS "char* password"

.PP
Password used for Login\&. 
.SS "char* path"

.PP
Path to the file\&. 
.SS "char* user"

.PP
User used for Login\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Download from the source code\&.
