.TH "download.h" 3 "Fri Dec 4 2020" "Version 1.00" "Download" \" -*- nroff -*-
.ad l
.nh
.SH NAME
download.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'args\&.h'\fP
.br
\fC#include 'connection\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Download from the source code\&.
