.TH "download.c" 3 "Fri Dec 4 2020" "Version 1.00" "Download" \" -*- nroff -*-
.ad l
.nh
.SH NAME
download.c
.SH SYNOPSIS
.br
.PP
\fC#include 'download\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.RI "Main function called to execute the download\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Main function called to execute the download\&. 
.PP
\fBParameters\fP
.RS 4
\fIargc\fP number of arguments 
.br
\fIargv\fP value of the arguments 
.RE
.PP
\fBReturns\fP
.RS 4
int return value 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Download from the source code\&.
