RCOM PROJ: Data_Connection_Protocol
Data_Connection_Protocol
Data Structures
struct linkLayer
Struct to hold information about the Link Layer.
Functions
int llopen (int porta, int type)
Abre uma ligação de dados com a porta série.
int llwrite (int fd, char *buffer, int lenght)
int llread (int fd, unsigned char *buffer)
int llclose (int fd)
Variables
static struct sigaction old_action
sigaction to restore SIGALRN handler
struct linkLayer linkLayer
Data relative to the link layer.
struct termios oldtio
used in llclose to reset termios
volatile int failed
used in the alarm handler
Detailed Description
Function Documentation
llclose()
int llclose (int fd)
Parameters
fd identificador da ligação de dados
Returns
int valor positivo em caso de sucesso ou -1 em caso de erro
References log_error(), log_success(), old_action, oldtio, RECEIVER, receiver_DISC_UA(), linkLayer::status, TRANSMITTER, and transmitter_DISC_UA().
Referenced by main().
llopen()
int llopen (int porta, int type)
Abre uma ligação de dados com a porta série.
Parameters
porta número da porta x em "/dev/ttySx"
type TRANSMITTER|RECEIVER
Returns
int identificador da ligação de dados OU -1 em caso de erro
References atende(), initConnection(), log_error(), old_action, RECEIVER, receiver_UA(), linkLayer::status, TRANSMITTER, and transmitter_SET().
Referenced by main().
llread()
int llread (int fd, unsigned char * buffer)
Parameters
fd identificador da ligação de dados
buffer array de caracteres recebidos
Returns
int comprimento do array (número de caracteres lidos) ou -1 em caso de erro
References A_ER, BCC, C_I, FLAG, log_error(), Read, readingCycle(), readR, linkLayer::sequenceNumber, Start, and stateMachineSetUp().
Referenced by receiverApp().
llwrite()
int llwrite (int fd, char * buffer, int lenght)
Parameters
fd identificador da ligação de dados
buffer array de caracteres a transmitir
lenght comprimento do array de caracteres
Returns
int numero de caracteres escritos ou -1 em caso de erro
References A_ER, BCC, C_I, C_RR, fillFinalBuffer(), FLAG, log_error(), MAX_SIZE, linkLayer::sequenceNumber, Start, stateMachineSetUp(), Write, writeCycle(), and writeR.
Referenced by transmitterApp().
Variable Documentation
failed
volatile int failed
used in the alarm handler
Referenced by atende(), transmitter_DISC_UA(), transmitter_SET(), and writeCycle().
linkLayer
struct linkLayer linkLayer
Data relative to the link layer.
old_action
struct sigaction old_action static
sigaction to restore SIGALRN handler
Referenced by llclose(), and llopen().
oldtio
struct termios oldtio
used in llclose to reset termios
Referenced by initConnection(), and llclose().