RCOM PROJ: Application
Application
Data Structures
struct applicationLayer
Struct to save data relative to the Application.
Functions
void parseArgs (int argc, char **argv)
Função para dar parse dos argumentos da linah de comandos.
int transmitterApp (int fd)
Transmitter part of the application.
void parseFileInfo (unsigned char *controlpackage, int packagesize)
Parses the info of a Control Package to the Application Layer Struct.
int receiverApp (int fd)
Receiver part of the application.
int main (int argc, char **argv)
Variables
static struct applicationLayer applayer
Detailed Description
Function Documentation
main()
int main (int argc, char ** argv)
Parameters
argc valor esperado: 3
argv argv[1] = receiver|transmitter argv[2]={0,1,10,11}
Returns
int
References applayer, applicationLayer::gate, llclose(), llopen(), log_error(), log_success(), parseArgs(), RECEIVER, receiverApp(), TRANSMITTER, transmitterApp(), and applicationLayer::type.
parseArgs()
void parseArgs (int argc, char ** argv)
Função para dar parse dos argumentos da linah de comandos.
Parameters
argc argc de main
argv argv de main
References applayer, applicationLayer::destinationArg, applicationLayer::filenameArg, applicationLayer::gate, log_caution(), log_error(), RECEIVER, TRANSMITTER, and applicationLayer::type.
Referenced by main().
parseFileInfo()
void parseFileInfo (unsigned char * controlpackage, int packagesize)
Parses the info of a Control Package to the Application Layer Struct.
Parameters
controlpackage Control Package
References applayer, applicationLayer::filename, applicationLayer::filesize, T_NAME, and T_SIZE.
Referenced by receiverApp().
receiverApp()
int receiverApp (int fd)
Receiver part of the application.
Parameters
fd file descriptor of connection
Returns
int 0 if all okay, negative otherwise
References applayer, DATA, applicationLayer::destinationArg, END, applicationLayer::filename, llread(), log_caution(), log_error(), MAX_SIZE, parseFileInfo(), and START.
Referenced by main().
transmitterApp()
int transmitterApp (int fd)
Transmitter part of the application.
Parameters
fd file descriptor of connection
Returns
int 0 if all okay, negative otherwise
References applayer, DATA, END, applicationLayer::filenameArg, llwrite(), log_error(), MAX_SIZE, START, T_NAME, and T_SIZE.
Referenced by main().
Variable Documentation
applayer
struct applicationLayer applayer static
Referenced by main(), parseArgs(), parseFileInfo(), receiverApp(), and transmitterApp().