RCOM PROJ: State_Machine
State_Machine
Data Structures
struct stateMachineParams
List of Parameters to Personalize the State Machine.
Enumerations
enum stateMachineType { Supervision, Write, Read }
enum stateMachineState {
Start, FLAG_RCV, A_RCV, C_RCV,
BCC_OK, DONE
}
Functions
void stateMachineSetUp (unsigned char control, unsigned char address, enum stateMachineState state, enum stateMachineType type)
Function to easily change the State Machine.
int stateMachine (unsigned char byte, unsigned char **buf, int *size)
The StateMachine function that processes a byte and updates it's state.
int processStart (unsigned char byte)
Function to process a byte in case the state is Start.
int processFLAG_RCV (unsigned char byte)
Function to process a byte in case the state is FLAG_RCV.
int processA_RCV (unsigned char byte)
Function to process a byte in case the state is A_RCV.
int processC_RCV (unsigned char byte)
Function to process a byte in case the state is C_RCV.
int processBCC_OK (unsigned char byte, unsigned char **buffer, int *buffersize)
Function to process a byte in case the state is BCC_OK.
Variables
static unsigned checkBuffer [2]
static int frameIndex
static int wrongC
struct stateMachineParams state_machine
Detailed Description
Enumeration Type Documentation
stateMachineState
enum stateMachineState
Enumerator
Start
FLAG_RCV
A_RCV
C_RCV
BCC_OK
DONE
stateMachineType
enum stateMachineType
Enumerator
Supervision
Write
Read
Function Documentation
processA_RCV()
int processA_RCV (unsigned char byte)
Function to process a byte in case the state is A_RCV.
Parameters
byte byte to be processed
Returns
int negative value in case of error, 0 otherwise
References C_I, C_RCV, C_REJ, checkBuffer, stateMachineParams::control, FLAG, FLAG_RCV, frameIndex, log_caution(), log_error(), Read, linkLayer::sequenceNumber, Start, stateMachineParams::state, state_machine, Supervision, TRUE, stateMachineParams::type, Write, and wrongC.
Referenced by stateMachine().
processBCC_OK()
int processBCC_OK (unsigned char byte, unsigned char ** buffer, int * buffersize)
Function to process a byte in case the state is BCC_OK.
Parameters
byte byte to be processed
buffer buffer to put data if stateMachineType is Read
buffersize variable to keeo size of buf if stateMachineType is Read
Returns
int negative value in case of error, 0 otherwise
References DONE, FLAG, linkLayer::frame, frameIndex, log_error(), Read, linkLayer::sequenceNumber, Start, stateMachineParams::state, state_machine, Supervision, stateMachineParams::type, and Write.
Referenced by stateMachine().
processC_RCV()
int processC_RCV (unsigned char byte)
Function to process a byte in case the state is C_RCV.
Parameters
byte byte to be processed
Returns
int negative value in case of error, 0 otherwise
References BCC, BCC_OK, checkBuffer, FLAG, FLAG_RCV, frameIndex, log_caution(), log_error(), Read, Start, stateMachineParams::state, state_machine, Supervision, TRUE, stateMachineParams::type, Write, and wrongC.
Referenced by stateMachine().
processFLAG_RCV()
int processFLAG_RCV (unsigned char byte)
Function to process a byte in case the state is FLAG_RCV.
Parameters
byte byte to be processed
Returns
int negative value in case of error, 0 otherwise
References A_RCV, stateMachineParams::address, checkBuffer, FLAG, frameIndex, Read, Start, stateMachineParams::state, state_machine, and stateMachineParams::type.
Referenced by stateMachine().
processStart()
int processStart (unsigned char byte)
Function to process a byte in case the state is Start.
Parameters
byte byte to be processed
Returns
int negative value in case of error, 0 otherwise
References FALSE, FLAG, FLAG_RCV, frameIndex, Read, stateMachineParams::state, state_machine, stateMachineParams::type, and wrongC.
Referenced by stateMachine().
stateMachine()
int stateMachine (unsigned char byte, unsigned char ** buf, int * size)
The StateMachine function that processes a byte and updates it's state.
Parameters
byte byte to process
buf buffer to put data if stateMachineType is Read
size variable to keeo size of buf if stateMachineType is Read
Returns
int negative value in case of error, 0 otherwise
References A_RCV, BCC_OK, C_RCV, DONE, FLAG_RCV, linkLayer::frame, frameIndex, log_error(), processA_RCV(), processBCC_OK(), processC_RCV(), processFLAG_RCV(), processStart(), Read, Start, stateMachineParams::state, state_machine, and stateMachineParams::type.
Referenced by readingCycle(), and writeCycle().
stateMachineSetUp()
void stateMachineSetUp (unsigned char control, unsigned char address, enum stateMachineState state, enum stateMachineType type)
Function to easily change the State Machine.
Parameters
control Control Byte that is suppossed to be received
address Address Byte that is suppossed to be received
state State of the State Machine
type Type of State Machine
References stateMachineParams::address, stateMachineParams::control, stateMachineParams::state, state_machine, and stateMachineParams::type.
Referenced by llread(), llwrite(), receiver_DISC_UA(), receiver_UA(), transmitter_DISC_UA(), and transmitter_SET().
Variable Documentation
checkBuffer
unsigned checkBuffer[2] static
Referenced by processA_RCV(), processC_RCV(), and processFLAG_RCV().
frameIndex
int frameIndex static
Referenced by processA_RCV(), processBCC_OK(), processC_RCV(), processFLAG_RCV(), processStart(), and stateMachine().
state_machine
struct stateMachineParams state_machine
Referenced by atende(), processA_RCV(), processBCC_OK(), processC_RCV(), processFLAG_RCV(), processStart(), readingCycle(), stateMachine(), stateMachineSetUp(), and writeCycle().
wrongC
int wrongC static
Referenced by processA_RCV(), processC_RCV(), and processStart().