RCOM PROJ: src/logs.c File Reference
logs.c File Reference
#include "logs.h"
Functions
void log_error (char *arr)
Outputs a message in red.
void log_caution (char *arr)
Outputs a message in yellow.
void log_success (char *arr)
Outputs a message in green.
void log_message (char *arr)
Outputs a message in white.
void log_message_number (char *arr, int numb)
Outputs a message in the form "number - message".
void log_hexa (unsigned char a)
Outputs a message in the form "Content: 0xHH".
void log_received_message (unsigned char *buf, int size)
Outputs a message (String) received by llread.
Function Documentation
log_caution()
void log_caution (char * arr)
Outputs a message in yellow.
Parameters
arr message String
References RESET, and YELLOW.
Referenced by atende(), parseArgs(), processA_RCV(), processC_RCV(), readingCycle(), receiverApp(), and writeCycle().
log_error()
void log_error (char * arr)
Outputs a message in red.
Parameters
arr message String
References RED, and RESET.
Referenced by initConnection(), llclose(), llopen(), llread(), llwrite(), main(), parseArgs(), processA_RCV(), processBCC_OK(), processC_RCV(), readingCycle(), receiver_DISC_UA(), receiver_UA(), receiverApp(), stateMachine(), transmitter_DISC_UA(), transmitter_SET(), transmitterApp(), and writeCycle().
log_hexa()
void log_hexa (unsigned char a)
Outputs a message in the form "Content: 0xHH".
Parameters
a Byte
log_message()
void log_message (char * arr)
Outputs a message in white.
Parameters
arr message String
log_message_number()
void log_message_number (char * arr, int numb)
Outputs a message in the form "number - message".
Parameters
arr message String
numb number
log_received_message()
void log_received_message (unsigned char * buf, int size)
Outputs a message (String) received by llread.
Parameters
buf message Buffer
size Size of the message
log_success()
void log_success (char * arr)
Outputs a message in green.
Parameters
arr message String
References GREEN, and RESET.
Referenced by initConnection(), llclose(), and main().